### ISSUE TITLE
Exclude creator of PR from mentioning

### ISSUE THREAD

**Issue by LukasReschke** [facebook/mention-bot#66]
For example https://github.com/owncloud/core/pull/21287 should probably not mention our beloved @DeepDiver1975 :smile:

**Comment by LukasReschke** [comment]
https://github.com/facebook/mention-bot/pull/19 claims to have fixed this. Spooky :ghost:

**Comment by vjeux** [comment]
How did you setup the bot? Maybe you have an older version?

**Comment by LukasReschke** [comment]
We are lazy and just use mention-bot.herokuapp.com as described at https://github.com/facebook/mention-bot#how-to-use

**Comment by vjeux** [comment]
Hmm this is sad then, I really thought it was fixed.

**Comment by DeepDiver1975** [comment]
> We are lazy

... yes - we are ....

**Comment by caarlos0** [comment]
I think this is working this way already...

**Comment by vjeux** [comment]
I realized that I didn't push things to heroku in a long time. Probably didn't pick up the changes. Let me know if it's still not working.

**Comment by bgw** [comment]
Still broken: https://github.com/ParsePlatform/parse-dashboard/pull/123
